name: CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker build -t $DOCKER_IMAGE .
          docker tag $DOCKER_IMAGE $CI_REGISTRY_IMAGE/$DOCKER_IMAGE:$DOCKER_TAG

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker run $CI_REGISTRY_IMAGE/$DOCKER_IMAGE:$DOCKER_TAG /bin/true

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE:$DOCKER_TAG
