name: CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install -r requirements.txt
          python setup.py build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install -r requirements.txt
          pip install pytest
          pytest tests/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install -r requirements.txt
          python setup.py install
